-- Creating the Table
ALTER TABLE Customers
ADD IsVIP CHAR(1) DEFAULT 'N';

CREATE TABLE AuditLog(
    LogID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    TransactionID NUMBER,
    LogDate DATE,
    Action VARCHAR2(100)
);

-- SC-1
-- Scenario 1: Discount loan interest for customers above 60
BEGIN
    FOR c IN (
        SELECT CustomerID,
               FLOOR(MONTHS_BETWEEN(SYSDATE,DOB)/12) Age
        FROM Customers
    )
    LOOP
        IF c.Age > 60 THEN
            UPDATE Loans
            SET InterestRate = InterestRate - 1
            WHERE CustomerID = c.CustomerID;
        END IF;
    END LOOP;

    COMMIT;
END;
/